version: 0.0
os: linux
files:
  - source: var/www/html
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: "*.php"
    owner: apache
    group: apache
    mode: "0644"
    type:
      - file

#hooks:
#   AfterInstall:
#   - location: Scripts/ChownChmodDocumentRoot_html.sh
#     timeout: 180
#     runas: root
